/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLayoutImport } from './routes/auth/_layout'
import { Route as AuthLayoutVerifyAccountImport } from './routes/auth/_layout.verify-account'
import { Route as AuthLayoutRegisterImport } from './routes/auth/_layout.register'
import { Route as AuthLayoutLoginImport } from './routes/auth/_layout.login'
import { Route as AuthLayoutForgotPasswordImport } from './routes/auth/_layout.forgot-password'
import { Route as AuthLayoutAccountValidatedImport } from './routes/auth/_layout.account-validated'
import { Route as AuthLayoutAccountCreatedImport } from './routes/auth/_layout.account-created'
import { Route as AuthenticatedRecipesNewImport } from './routes/_authenticated/recipes/new'
import { Route as AuthenticatedRecipesRecipeIdImport } from './routes/_authenticated/recipes/$recipeId'

// Create Virtual Routes

const AuthImport = createFileRoute('/auth')()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLayoutVerifyAccountRoute = AuthLayoutVerifyAccountImport.update({
  id: '/verify-account',
  path: '/verify-account',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutRegisterRoute = AuthLayoutRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutLoginRoute = AuthLayoutLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutForgotPasswordRoute = AuthLayoutForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutAccountValidatedRoute = AuthLayoutAccountValidatedImport.update(
  {
    id: '/account-validated',
    path: '/account-validated',
    getParentRoute: () => AuthLayoutRoute,
  } as any,
)

const AuthLayoutAccountCreatedRoute = AuthLayoutAccountCreatedImport.update({
  id: '/account-created',
  path: '/account-created',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthenticatedRecipesNewRoute = AuthenticatedRecipesNewImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedRecipesRecipeIdRoute =
  AuthenticatedRecipesRecipeIdImport.update({
    id: '/recipes/$recipeId',
    path: '/recipes/$recipeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/recipes/$recipeId': {
      id: '/_authenticated/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof AuthenticatedRecipesRecipeIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/recipes/new': {
      id: '/_authenticated/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AuthenticatedRecipesNewImport
      parentRoute: typeof AuthenticatedImport
    }
    '/auth/_layout/account-created': {
      id: '/auth/_layout/account-created'
      path: '/account-created'
      fullPath: '/auth/account-created'
      preLoaderRoute: typeof AuthLayoutAccountCreatedImport
      parentRoute: typeof AuthLayoutImport
    }
    '/auth/_layout/account-validated': {
      id: '/auth/_layout/account-validated'
      path: '/account-validated'
      fullPath: '/auth/account-validated'
      preLoaderRoute: typeof AuthLayoutAccountValidatedImport
      parentRoute: typeof AuthLayoutImport
    }
    '/auth/_layout/forgot-password': {
      id: '/auth/_layout/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthLayoutForgotPasswordImport
      parentRoute: typeof AuthLayoutImport
    }
    '/auth/_layout/login': {
      id: '/auth/_layout/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLayoutLoginImport
      parentRoute: typeof AuthLayoutImport
    }
    '/auth/_layout/register': {
      id: '/auth/_layout/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthLayoutRegisterImport
      parentRoute: typeof AuthLayoutImport
    }
    '/auth/_layout/verify-account': {
      id: '/auth/_layout/verify-account'
      path: '/verify-account'
      fullPath: '/auth/verify-account'
      preLoaderRoute: typeof AuthLayoutVerifyAccountImport
      parentRoute: typeof AuthLayoutImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedRecipesRecipeIdRoute: typeof AuthenticatedRecipesRecipeIdRoute
  AuthenticatedRecipesNewRoute: typeof AuthenticatedRecipesNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedRecipesRecipeIdRoute: AuthenticatedRecipesRecipeIdRoute,
  AuthenticatedRecipesNewRoute: AuthenticatedRecipesNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthLayoutAccountCreatedRoute: typeof AuthLayoutAccountCreatedRoute
  AuthLayoutAccountValidatedRoute: typeof AuthLayoutAccountValidatedRoute
  AuthLayoutForgotPasswordRoute: typeof AuthLayoutForgotPasswordRoute
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
  AuthLayoutRegisterRoute: typeof AuthLayoutRegisterRoute
  AuthLayoutVerifyAccountRoute: typeof AuthLayoutVerifyAccountRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutAccountCreatedRoute: AuthLayoutAccountCreatedRoute,
  AuthLayoutAccountValidatedRoute: AuthLayoutAccountValidatedRoute,
  AuthLayoutForgotPasswordRoute: AuthLayoutForgotPasswordRoute,
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
  AuthLayoutRegisterRoute: AuthLayoutRegisterRoute,
  AuthLayoutVerifyAccountRoute: AuthLayoutVerifyAccountRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/recipes/$recipeId': typeof AuthenticatedRecipesRecipeIdRoute
  '/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/auth/account-created': typeof AuthLayoutAccountCreatedRoute
  '/auth/account-validated': typeof AuthLayoutAccountValidatedRoute
  '/auth/forgot-password': typeof AuthLayoutForgotPasswordRoute
  '/auth/login': typeof AuthLayoutLoginRoute
  '/auth/register': typeof AuthLayoutRegisterRoute
  '/auth/verify-account': typeof AuthLayoutVerifyAccountRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/recipes/$recipeId': typeof AuthenticatedRecipesRecipeIdRoute
  '/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/auth/account-created': typeof AuthLayoutAccountCreatedRoute
  '/auth/account-validated': typeof AuthLayoutAccountValidatedRoute
  '/auth/forgot-password': typeof AuthLayoutForgotPasswordRoute
  '/auth/login': typeof AuthLayoutLoginRoute
  '/auth/register': typeof AuthLayoutRegisterRoute
  '/auth/verify-account': typeof AuthLayoutVerifyAccountRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/_layout': typeof AuthLayoutRouteWithChildren
  '/_authenticated/recipes/$recipeId': typeof AuthenticatedRecipesRecipeIdRoute
  '/_authenticated/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/auth/_layout/account-created': typeof AuthLayoutAccountCreatedRoute
  '/auth/_layout/account-validated': typeof AuthLayoutAccountValidatedRoute
  '/auth/_layout/forgot-password': typeof AuthLayoutForgotPasswordRoute
  '/auth/_layout/login': typeof AuthLayoutLoginRoute
  '/auth/_layout/register': typeof AuthLayoutRegisterRoute
  '/auth/_layout/verify-account': typeof AuthLayoutVerifyAccountRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/auth'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/auth/account-created'
    | '/auth/account-validated'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-account'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/auth'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/auth/account-created'
    | '/auth/account-validated'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-account'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/auth/_layout'
    | '/_authenticated/recipes/$recipeId'
    | '/_authenticated/recipes/new'
    | '/auth/_layout/account-created'
    | '/auth/_layout/account-validated'
    | '/auth/_layout/forgot-password'
    | '/auth/_layout/login'
    | '/auth/_layout/register'
    | '/auth/_layout/verify-account'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/recipes/$recipeId",
        "/_authenticated/recipes/new"
      ]
    },
    "/auth": {
      "filePath": "auth",
      "children": [
        "/auth/_layout"
      ]
    },
    "/auth/_layout": {
      "filePath": "auth/_layout.tsx",
      "parent": "/auth",
      "children": [
        "/auth/_layout/account-created",
        "/auth/_layout/account-validated",
        "/auth/_layout/forgot-password",
        "/auth/_layout/login",
        "/auth/_layout/register",
        "/auth/_layout/verify-account"
      ]
    },
    "/_authenticated/recipes/$recipeId": {
      "filePath": "_authenticated/recipes/$recipeId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/recipes/new": {
      "filePath": "_authenticated/recipes/new.tsx",
      "parent": "/_authenticated"
    },
    "/auth/_layout/account-created": {
      "filePath": "auth/_layout.account-created.tsx",
      "parent": "/auth/_layout"
    },
    "/auth/_layout/account-validated": {
      "filePath": "auth/_layout.account-validated.tsx",
      "parent": "/auth/_layout"
    },
    "/auth/_layout/forgot-password": {
      "filePath": "auth/_layout.forgot-password.tsx",
      "parent": "/auth/_layout"
    },
    "/auth/_layout/login": {
      "filePath": "auth/_layout.login.tsx",
      "parent": "/auth/_layout"
    },
    "/auth/_layout/register": {
      "filePath": "auth/_layout.register.tsx",
      "parent": "/auth/_layout"
    },
    "/auth/_layout/verify-account": {
      "filePath": "auth/_layout.verify-account.tsx",
      "parent": "/auth/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
