/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RecipesOldImport } from './routes/recipes-old'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as RecipesOldNewImport } from './routes/recipes-old/new'
import { Route as RecipesOldRecipeIdImport } from './routes/recipes-old/$recipeId'
import { Route as AuthLayoutImport } from './routes/auth/_layout'
import { Route as AuthenticatedRecipesImport } from './routes/_authenticated/recipes'
import { Route as AuthenticatedFavoritesImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedRecipesIndexImport } from './routes/_authenticated/recipes/index'
import { Route as AuthLayoutVerifyAccountImport } from './routes/auth/_layout.verify-account'
import { Route as AuthLayoutRegisterImport } from './routes/auth/_layout.register'
import { Route as AuthLayoutLoginImport } from './routes/auth/_layout.login'
import { Route as AuthLayoutForgotPasswordImport } from './routes/auth/_layout.forgot-password'
import { Route as AuthLayoutAccountValidatedImport } from './routes/auth/_layout.account-validated'
import { Route as AuthLayoutAccountCreatedImport } from './routes/auth/_layout.account-created'
import { Route as AuthenticatedRecipesNewImport } from './routes/_authenticated/recipes/new'
import { Route as AuthenticatedRecipesRecipeIdImport } from './routes/_authenticated/recipes/$recipeId'
import { Route as AuthenticatedCategoriesTypeImport } from './routes/_authenticated/categories/$type'

// Create Virtual Routes

const AuthImport = createFileRoute('/auth')()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const RecipesOldRoute = RecipesOldImport.update({
  id: '/recipes-old',
  path: '/recipes-old',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RecipesOldNewRoute = RecipesOldNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RecipesOldRoute,
} as any)

const RecipesOldRecipeIdRoute = RecipesOldRecipeIdImport.update({
  id: '/$recipeId',
  path: '/$recipeId',
  getParentRoute: () => RecipesOldRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)

const AuthenticatedRecipesRoute = AuthenticatedRecipesImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedFavoritesRoute = AuthenticatedFavoritesImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedRecipesIndexRoute = AuthenticatedRecipesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRecipesRoute,
} as any)

const AuthLayoutVerifyAccountRoute = AuthLayoutVerifyAccountImport.update({
  id: '/verify-account',
  path: '/verify-account',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutRegisterRoute = AuthLayoutRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutLoginRoute = AuthLayoutLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutForgotPasswordRoute = AuthLayoutForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutAccountValidatedRoute = AuthLayoutAccountValidatedImport.update(
  {
    id: '/account-validated',
    path: '/account-validated',
    getParentRoute: () => AuthLayoutRoute,
  } as any,
)

const AuthLayoutAccountCreatedRoute = AuthLayoutAccountCreatedImport.update({
  id: '/account-created',
  path: '/account-created',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthenticatedRecipesNewRoute = AuthenticatedRecipesNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRecipesRoute,
} as any)

const AuthenticatedRecipesRecipeIdRoute =
  AuthenticatedRecipesRecipeIdImport.update({
    id: '/$recipeId',
    path: '/$recipeId',
    getParentRoute: () => AuthenticatedRecipesRoute,
  } as any)

const AuthenticatedCategoriesTypeRoute =
  AuthenticatedCategoriesTypeImport.update({
    id: '/categories/$type',
    path: '/categories/$type',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/recipes-old': {
      id: '/recipes-old'
      path: '/recipes-old'
      fullPath: '/recipes-old'
      preLoaderRoute: typeof RecipesOldImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/recipes': {
      id: '/_authenticated/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthenticatedRecipesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof AuthRoute
    }
    '/recipes-old/$recipeId': {
      id: '/recipes-old/$recipeId'
      path: '/$recipeId'
      fullPath: '/recipes-old/$recipeId'
      preLoaderRoute: typeof RecipesOldRecipeIdImport
      parentRoute: typeof RecipesOldImport
    }
    '/recipes-old/new': {
      id: '/recipes-old/new'
      path: '/new'
      fullPath: '/recipes-old/new'
      preLoaderRoute: typeof RecipesOldNewImport
      parentRoute: typeof RecipesOldImport
    }
    '/_authenticated/categories/$type': {
      id: '/_authenticated/categories/$type'
      path: '/categories/$type'
      fullPath: '/categories/$type'
      preLoaderRoute: typeof AuthenticatedCategoriesTypeImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/recipes/$recipeId': {
      id: '/_authenticated/recipes/$recipeId'
      path: '/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof AuthenticatedRecipesRecipeIdImport
      parentRoute: typeof AuthenticatedRecipesImport
    }
    '/_authenticated/recipes/new': {
      id: '/_authenticated/recipes/new'
      path: '/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AuthenticatedRecipesNewImport
      parentRoute: typeof AuthenticatedRecipesImport
    }
    '/auth/_layout/account-created': {
      id: '/auth/_layout/account-created'
      path: '/account-created'
      fullPath: '/auth/account-created'
      preLoaderRoute: typeof AuthLayoutAccountCreatedImport
      parentRoute: typeof AuthLayoutImport
    }
    '/auth/_layout/account-validated': {
      id: '/auth/_layout/account-validated'
      path: '/account-validated'
      fullPath: '/auth/account-validated'
      preLoaderRoute: typeof AuthLayoutAccountValidatedImport
      parentRoute: typeof AuthLayoutImport
    }
    '/auth/_layout/forgot-password': {
      id: '/auth/_layout/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthLayoutForgotPasswordImport
      parentRoute: typeof AuthLayoutImport
    }
    '/auth/_layout/login': {
      id: '/auth/_layout/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLayoutLoginImport
      parentRoute: typeof AuthLayoutImport
    }
    '/auth/_layout/register': {
      id: '/auth/_layout/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthLayoutRegisterImport
      parentRoute: typeof AuthLayoutImport
    }
    '/auth/_layout/verify-account': {
      id: '/auth/_layout/verify-account'
      path: '/verify-account'
      fullPath: '/auth/verify-account'
      preLoaderRoute: typeof AuthLayoutVerifyAccountImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_authenticated/recipes/': {
      id: '/_authenticated/recipes/'
      path: '/'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthenticatedRecipesIndexImport
      parentRoute: typeof AuthenticatedRecipesImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRecipesRouteChildren {
  AuthenticatedRecipesRecipeIdRoute: typeof AuthenticatedRecipesRecipeIdRoute
  AuthenticatedRecipesNewRoute: typeof AuthenticatedRecipesNewRoute
  AuthenticatedRecipesIndexRoute: typeof AuthenticatedRecipesIndexRoute
}

const AuthenticatedRecipesRouteChildren: AuthenticatedRecipesRouteChildren = {
  AuthenticatedRecipesRecipeIdRoute: AuthenticatedRecipesRecipeIdRoute,
  AuthenticatedRecipesNewRoute: AuthenticatedRecipesNewRoute,
  AuthenticatedRecipesIndexRoute: AuthenticatedRecipesIndexRoute,
}

const AuthenticatedRecipesRouteWithChildren =
  AuthenticatedRecipesRoute._addFileChildren(AuthenticatedRecipesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedRecipesRoute: typeof AuthenticatedRecipesRouteWithChildren
  AuthenticatedCategoriesTypeRoute: typeof AuthenticatedCategoriesTypeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedRecipesRoute: AuthenticatedRecipesRouteWithChildren,
  AuthenticatedCategoriesTypeRoute: AuthenticatedCategoriesTypeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface RecipesOldRouteChildren {
  RecipesOldRecipeIdRoute: typeof RecipesOldRecipeIdRoute
  RecipesOldNewRoute: typeof RecipesOldNewRoute
}

const RecipesOldRouteChildren: RecipesOldRouteChildren = {
  RecipesOldRecipeIdRoute: RecipesOldRecipeIdRoute,
  RecipesOldNewRoute: RecipesOldNewRoute,
}

const RecipesOldRouteWithChildren = RecipesOldRoute._addFileChildren(
  RecipesOldRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthLayoutAccountCreatedRoute: typeof AuthLayoutAccountCreatedRoute
  AuthLayoutAccountValidatedRoute: typeof AuthLayoutAccountValidatedRoute
  AuthLayoutForgotPasswordRoute: typeof AuthLayoutForgotPasswordRoute
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
  AuthLayoutRegisterRoute: typeof AuthLayoutRegisterRoute
  AuthLayoutVerifyAccountRoute: typeof AuthLayoutVerifyAccountRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutAccountCreatedRoute: AuthLayoutAccountCreatedRoute,
  AuthLayoutAccountValidatedRoute: AuthLayoutAccountValidatedRoute,
  AuthLayoutForgotPasswordRoute: AuthLayoutForgotPasswordRoute,
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
  AuthLayoutRegisterRoute: AuthLayoutRegisterRoute,
  AuthLayoutVerifyAccountRoute: AuthLayoutVerifyAccountRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/recipes-old': typeof RecipesOldRouteWithChildren
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/recipes': typeof AuthenticatedRecipesRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/recipes-old/$recipeId': typeof RecipesOldRecipeIdRoute
  '/recipes-old/new': typeof RecipesOldNewRoute
  '/categories/$type': typeof AuthenticatedCategoriesTypeRoute
  '/recipes/$recipeId': typeof AuthenticatedRecipesRecipeIdRoute
  '/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/auth/account-created': typeof AuthLayoutAccountCreatedRoute
  '/auth/account-validated': typeof AuthLayoutAccountValidatedRoute
  '/auth/forgot-password': typeof AuthLayoutForgotPasswordRoute
  '/auth/login': typeof AuthLayoutLoginRoute
  '/auth/register': typeof AuthLayoutRegisterRoute
  '/auth/verify-account': typeof AuthLayoutVerifyAccountRoute
  '/recipes/': typeof AuthenticatedRecipesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/recipes-old': typeof RecipesOldRouteWithChildren
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/recipes-old/$recipeId': typeof RecipesOldRecipeIdRoute
  '/recipes-old/new': typeof RecipesOldNewRoute
  '/categories/$type': typeof AuthenticatedCategoriesTypeRoute
  '/recipes/$recipeId': typeof AuthenticatedRecipesRecipeIdRoute
  '/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/auth/account-created': typeof AuthLayoutAccountCreatedRoute
  '/auth/account-validated': typeof AuthLayoutAccountValidatedRoute
  '/auth/forgot-password': typeof AuthLayoutForgotPasswordRoute
  '/auth/login': typeof AuthLayoutLoginRoute
  '/auth/register': typeof AuthLayoutRegisterRoute
  '/auth/verify-account': typeof AuthLayoutVerifyAccountRoute
  '/recipes': typeof AuthenticatedRecipesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/recipes-old': typeof RecipesOldRouteWithChildren
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/recipes': typeof AuthenticatedRecipesRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/_layout': typeof AuthLayoutRouteWithChildren
  '/recipes-old/$recipeId': typeof RecipesOldRecipeIdRoute
  '/recipes-old/new': typeof RecipesOldNewRoute
  '/_authenticated/categories/$type': typeof AuthenticatedCategoriesTypeRoute
  '/_authenticated/recipes/$recipeId': typeof AuthenticatedRecipesRecipeIdRoute
  '/_authenticated/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/auth/_layout/account-created': typeof AuthLayoutAccountCreatedRoute
  '/auth/_layout/account-validated': typeof AuthLayoutAccountValidatedRoute
  '/auth/_layout/forgot-password': typeof AuthLayoutForgotPasswordRoute
  '/auth/_layout/login': typeof AuthLayoutLoginRoute
  '/auth/_layout/register': typeof AuthLayoutRegisterRoute
  '/auth/_layout/verify-account': typeof AuthLayoutVerifyAccountRoute
  '/_authenticated/recipes/': typeof AuthenticatedRecipesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/recipes-old'
    | '/favorites'
    | '/recipes'
    | '/auth'
    | '/recipes-old/$recipeId'
    | '/recipes-old/new'
    | '/categories/$type'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/auth/account-created'
    | '/auth/account-validated'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-account'
    | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/recipes-old'
    | '/favorites'
    | '/auth'
    | '/recipes-old/$recipeId'
    | '/recipes-old/new'
    | '/categories/$type'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/auth/account-created'
    | '/auth/account-validated'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-account'
    | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/recipes-old'
    | '/_authenticated/favorites'
    | '/_authenticated/recipes'
    | '/auth'
    | '/auth/_layout'
    | '/recipes-old/$recipeId'
    | '/recipes-old/new'
    | '/_authenticated/categories/$type'
    | '/_authenticated/recipes/$recipeId'
    | '/_authenticated/recipes/new'
    | '/auth/_layout/account-created'
    | '/auth/_layout/account-validated'
    | '/auth/_layout/forgot-password'
    | '/auth/_layout/login'
    | '/auth/_layout/register'
    | '/auth/_layout/verify-account'
    | '/_authenticated/recipes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  RecipesOldRoute: typeof RecipesOldRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  RecipesOldRoute: RecipesOldRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/recipes-old",
        "/auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/favorites",
        "/_authenticated/recipes",
        "/_authenticated/categories/$type"
      ]
    },
    "/recipes-old": {
      "filePath": "recipes-old.tsx",
      "children": [
        "/recipes-old/$recipeId",
        "/recipes-old/new"
      ]
    },
    "/_authenticated/favorites": {
      "filePath": "_authenticated/favorites.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/recipes": {
      "filePath": "_authenticated/recipes.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/recipes/$recipeId",
        "/_authenticated/recipes/new",
        "/_authenticated/recipes/"
      ]
    },
    "/auth": {
      "filePath": "auth",
      "children": [
        "/auth/_layout"
      ]
    },
    "/auth/_layout": {
      "filePath": "auth/_layout.tsx",
      "parent": "/auth",
      "children": [
        "/auth/_layout/account-created",
        "/auth/_layout/account-validated",
        "/auth/_layout/forgot-password",
        "/auth/_layout/login",
        "/auth/_layout/register",
        "/auth/_layout/verify-account"
      ]
    },
    "/recipes-old/$recipeId": {
      "filePath": "recipes-old/$recipeId.tsx",
      "parent": "/recipes-old"
    },
    "/recipes-old/new": {
      "filePath": "recipes-old/new.tsx",
      "parent": "/recipes-old"
    },
    "/_authenticated/categories/$type": {
      "filePath": "_authenticated/categories/$type.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/recipes/$recipeId": {
      "filePath": "_authenticated/recipes/$recipeId.tsx",
      "parent": "/_authenticated/recipes"
    },
    "/_authenticated/recipes/new": {
      "filePath": "_authenticated/recipes/new.tsx",
      "parent": "/_authenticated/recipes"
    },
    "/auth/_layout/account-created": {
      "filePath": "auth/_layout.account-created.tsx",
      "parent": "/auth/_layout"
    },
    "/auth/_layout/account-validated": {
      "filePath": "auth/_layout.account-validated.tsx",
      "parent": "/auth/_layout"
    },
    "/auth/_layout/forgot-password": {
      "filePath": "auth/_layout.forgot-password.tsx",
      "parent": "/auth/_layout"
    },
    "/auth/_layout/login": {
      "filePath": "auth/_layout.login.tsx",
      "parent": "/auth/_layout"
    },
    "/auth/_layout/register": {
      "filePath": "auth/_layout.register.tsx",
      "parent": "/auth/_layout"
    },
    "/auth/_layout/verify-account": {
      "filePath": "auth/_layout.verify-account.tsx",
      "parent": "/auth/_layout"
    },
    "/_authenticated/recipes/": {
      "filePath": "_authenticated/recipes/index.tsx",
      "parent": "/_authenticated/recipes"
    }
  }
}
ROUTE_MANIFEST_END */
