# Configuration Docker Compose pour RecettesAirtable

services:
  # Service Ollama pour l'IA
  ollama:
    image: ollama/ollama:latest
    container_name: recettes-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend API
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: recettes-server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3.2:1b
      - FRONTEND_URL=http://localhost:3000
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
    depends_on:
      - ollama
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/.env:/app/.env:ro
    restart: unless-stopped

  # Frontend client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: recettes-client
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local